# Generated by Django 3.2 on 2021-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_developer_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
