# Generated by Django 3.2 on 2021-04-27 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_game_game_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={},
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='date_of_birth',
            new_name='founded',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='first_name',
            new_name='headquarters',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='date_of_death',
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game across whole library', primary_key=True, serialize=False),
        ),
    ]
