# Generated by Django 3.2 on 2021-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210427_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
    ]
