# Generated by Django 3.2 on 2021-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_game_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
