# Generated by Django 3.2 on 2021-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.IntegerField(),
        ),
    ]
