# Generated by Django 3.2 on 2021-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slideshow_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AddField(
            model_name='game',
            name='slideshow_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AddField(
            model_name='game',
            name='slideshow_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
    ]
