# Generated by Django 3.2 on 2021-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_developer_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
    ]
